### ISSUE TITLE
Training script argument.

### ISSUE THREAD

**Issue by otets-u** [NVlabs/SMERF#1]
Hello, I'm really intersted in this approach.

Now, I set up the enviroment by using Dockerfile.
And then, I'd like to know the argument for training script.

[Train and Evaluate](https://github.com/NVlabs/SMERF/tree/main?tab=readme-ov-file#train-and-evaluate)

Shall I select the confing from below folder??

- [openlanev2/configs](https://github.com/NVlabs/SMERF/tree/main/mmdetection3d/projects/openlanev2/configs)
- [toponet_openlanev2/configs](https://github.com/NVlabs/SMERF/tree/main/mmdetection3d/projects/toponet_openlanev2/configs)

Sincerely

**Comment by katieluo88** [comment]
Yes, that is correct! For example, to train a SMERF model on the OpenLane-V2 baseline with 8 GPUs, you should run the following command:

`bash tools/dist_train.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py 8`

The other configs are for [SMERF with the TopoNet model](https://github.com/NVlabs/SMERF/blob/main/mmdetection3d/projects/toponet_openlanev2/configs/toponet_smerf.py), and the baseline lane topology models without SD map. You may refer to the "Config" column of the [main results](https://github.com/NVlabs/SMERF?tab=readme-ov-file#main-results) table.

**Comment by otets-u** [comment]
Thank you for answering.

I followed your command and then I faced another error like the bottom.
Could you give me idea to solve this problem??


In addition, can I visualize the prediction result like video by below command??

bash tools/dist_test.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py ./openlaneV2BL_geodisjointsubset_sd_map_transformer.pth 8 --eval * [--eval-options visualization=True visualization_num=200]


[Supplementary video for Augmenting Lane Perception and Topology Understanding with Standard Definition Navigation Maps.](https://www.youtube.com/watch?v=hGt58oiMIDw)

Best regards.

```
root@a59f2907fad4:/workspace/OpenLane-V2/mmdetection3d# bash tools/dist_train.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py 2
/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 264, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 264, in <module>
    main()
  File "tools/train.py", line 180, in main
        main()cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))

  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump
  File "tools/train.py", line 180, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump
    f.write(self.pretty_text)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    f.write(self.pretty_text)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 680) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         tools/train.py FAILED         
=======================================
Root Cause:
[0]:
  time: 2024-01-24_10:56:12
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 680)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2024-01-24_10:56:12
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 681)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

```

**Comment by zhangmanCN** [comment]
> Thank you for answering.
> 
> I followed your command and then I faced another error like the bottom. Could you give me idea to solve this problem??
> 
> In addition, can I visualize the prediction result like video by below command??
> 
> bash tools/dist_test.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py ./openlaneV2BL_geodisjointsubset_sd_map_transformer.pth 8 --eval * [--eval-options visualization=True visualization_num=200]
> 
> [Supplementary video for Augmenting Lane Perception and Topology Understanding with Standard Definition Navigation Maps.](https://www.youtube.com/watch?v=hGt58oiMIDw)
> 
> Best regards.
> 
> ```
> root@a59f2907fad4:/workspace/OpenLane-V2/mmdetection3d# bash tools/dist_train.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py 2
> /opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
> and will be removed in future. Use torch.distributed.run.
> Note that --use_env is set by default in torch.distributed.run.
> If your script expects `--local_rank` argument to be set, please
> change it to read from `os.environ['LOCAL_RANK']` instead. See 
> https://pytorch.org/docs/stable/distributed.html#launch-utility for 
> further instructions
> 
>   warnings.warn(
> WARNING:torch.distributed.run:*****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> Traceback (most recent call last):
>   File "tools/train.py", line 264, in <module>
> Traceback (most recent call last):
>   File "tools/train.py", line 264, in <module>
>     main()
>   File "tools/train.py", line 180, in main
>         main()cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
> 
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump
>   File "tools/train.py", line 180, in main
>     cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump
>     f.write(self.pretty_text)
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
>     f.write(self.pretty_text)
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
>     text, _ = FormatCode(text, style_config=yapf_style, verify=True)
> TypeError: FormatCode() got an unexpected keyword argument 'verify'
>     text, _ = FormatCode(text, style_config=yapf_style, verify=True)
> TypeError: FormatCode() got an unexpected keyword argument 'verify'
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 680) of binary: /opt/conda/bin/python
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
>     main()
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
>     launch(args)
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
>     run(args)
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
>     elastic_launch(
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ***************************************
>          tools/train.py FAILED         
> =======================================
> Root Cause:
> [0]:
>   time: 2024-01-24_10:56:12
>   rank: 0 (local_rank: 0)
>   exitcode: 1 (pid: 680)
>   error_file: <N/A>
>   msg: "Process failed with exitcode 1"
> =======================================
> Other Failures:
> [1]:
>   time: 2024-01-24_10:56:12
>   rank: 1 (local_rank: 1)
>   exitcode: 1 (pid: 681)
>   error_file: <N/A>
>   msg: "Process failed with exitcode 1"
> ***************************************
> ```

It seems that this issue was caused by an incompatibility with the version of yapf. I resolved the problem by changing yapf from version 0.40.2 to 0.40.0.

**Comment by otets-u** [comment]
Thanks a lots.

I really appreciate your help. Let me ask 2 questions.

**Train**

After I updated yapf, and then I could pass the error.
`pip install yapf==0.40.0`

After that, the below error occuered.
It may occur due to the shortage of video.
I use 2 GPU card, RTX4070 with 12GB.

So, I'd like to try to change the batch_size. 
How can I change it??
I couldn't figure out the palce where the batch_size is set.

```
root@a59f2907fad4:/workspace/OpenLane-V2/mmdetection3d# bash tools/dist_train.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py 2
...

RuntimeError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 11.73 GiB total capacity; 10.03 GiB already allocated; 160.31 MiB free; 10.05 GiB reserved in total by PyTorch)
```

**Evaluation and Visualization**

Now, I try to use the trained model.
Can I see the visualized result below command??

```
root@a59f2907fad4:/workspace/OpenLane-V2/mmdetection3d# bash tools/dist_test.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py /workspace/openlaneV2BL_sd_map_transformer.pth 2 --eval * [--eval-options visualization=True visualization_num=200]
/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
load checkpoint from local path: /workspace/openlaneV2BL_sd_map_transformer.pth
load checkpoint from local path: /workspace/openlaneV2BL_sd_map_transformer.pth
[                                                  ] 0/64, elapsed: 0s, ETA:/opt/conda/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/opt/conda/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 64/64, 1.5 task/s, elapsed: 44s, ETA:     0s
*** Missing key [country / region] for a valid submission ***

calculating distances:: 100%|███████████████████| 64/64 [00:19<00:00,  3.37it/s]
/opt/conda/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py:641: RuntimeWarning: divide by zero encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
{'DET_l': 0.22929038, 'DET_t': 0.41278675, 'TOP_ll': 0.000545612650214897, 'TOP_lt': 0.18867358295237022, 'OpenLane-V2 Score': 0.27495030271048027, 'F-Score for 3D Lane': 0.34968080552401865}
```

**Comment by zhangmanCN** [comment]
**Train Question**
if you use the follow code to train your model and you want to change the batch size:
`bash tools/dist_train.sh projects/openlanev2/configs/baseline_large_ptsrep_smerf.py 8`
you should to change the value of `samples_per_gpu` in projects/openlanev2/configs/baseline_large_ptsrep_smerf.py. For others model config ,the method is same.
However, I find even setting the batch size to 1, training SMERF still requires around 32GB of VRAM. So, you might need to use a GPU with larger VRAM.
**Evaluation and Visualization**
Regarding SMERF, I haven't tried any visualization work yet, but based on my experience with TopoMLP, it is related to tools/test.py and the MMDET3D framework.

**Comment by katieluo88** [comment]
If you are running into GPU memory constraints, one possibility is to try the TopoNet baseline w/ or w/o SMERF. TopoNet is more performant and actually faster and more lightweight.

**Comment by otets-u** [comment]
Thank you for many helps.

I'm sorry for reply.
Finally, I could run the test script (tools/dist_test.sh).

I'd like to try this soon.

> If you are running into GPU memory constraints, one possibility is to try the TopoNet baseline w/ or w/o SMERF. TopoNet is more performant and actually faster and more lightweight.

Sincerely
