### ISSUE TITLE
SD preprocessing on openlanev2_subsetA

### ISSUE THREAD

**Issue by flywithcloud** [NVlabs/SMERF#11]
hello, thank you very much for your sharing and contribution. Can you make the SD preprocessing results (train/val/test_city.pkl) on the openlane-v2_subset_A public or make the precessing code to generate the train/val/test_city.pkl public?

**Comment by katieluo88** [comment]
Hi! While I cannot make the actual processed data available, the preprocessing instructions can be found in the [README](https://github.com/NVlabs/SMERF?tab=readme-ov-file#sd-map-processing). I didn't do anything special for the pickle files, but get the Argoverse GPS location of the city center. An example can be found in my issue [here](https://github.com/OpenDriveLab/OpenLane-V2/issues/52), regarding the OpenLane-V2 dataset. Let me know if this doesn't work for you!
