### ISSUE TITLE
Use the SDMap provided by OpenLaneV2

### ISSUE THREAD

**Issue by zhangmanCN** [NVlabs/SMERF#2]
Thank you for your great work!
I want to confirm how to use the SDMap provided by OpenLaneV2.
According to the code, I think if I want to use the SDMap provided by OpenLaneV2, I just need to set the ‘map_dir_prefix’ as ‘None’ in config file. Is this correct?
Looking forward to your reply ~

**Comment by Eagleflag88** [comment]
Hi,

Have you found the solution?
