### ISSUE TITLE
data_dict_subset_A_train.pkl

### ISSUE THREAD

**Issue by Bertram168** [NVlabs/SMERF#4]
Thank you for your work. Here I have a little question that I follow the command to process dataset using "python OpenLane-V2/preprocess.py", but I don't get the .pkl file(eg. data_dict_subset_A_train.pkl), what's wrong? How can I get the .pkl file?

**Comment by katieluo88** [comment]
Can you give a little more detail on this error? The code should be calling the [collect()](https://github.com/NVlabs/SMERF/blob/main/openlanev2/centerline/preprocessing/collect.py#L31) function from OpenLane-v2's `centerlane` package. This dumps the metadata into a pickle file located at `f'{root_path}/{collection}.pkl'` If you ran it without errors, maybe check to see if your root path is what you're expecting it to be? Generally, it's located in `data/OpenLane-V2/`.
