### ISSUE TITLE
 TOP_ll: 0.0000, TOP_lt: 0.0000

### ISSUE THREAD

**Issue by lee8856** [NVlabs/SMERF#5]
Thank you for your work. Here I have a little question when training or evaluating model the results are TOP_ll: 0.0000, TOP_lt: 0.0000. And also there was a prompt message "*** Missing key [country / region] for a valid submission ***"(I have download full dataset and SDMap data, also I have run preprocess.py to generate the pkl files)
I wonder how can I fix it. Looking forward to your reply.
Best regards.

**Comment by katieluo88** [comment]
Hi! Can you provide a bit more details about how you're training the model? Make sure that the setup is correct, and start by running the baseline model: `bash tools/dist_train.sh projects/openlanev2/configs/baseline_large_ptsrep.py [NUM_GPUS]` without using the SD maps. 

If you cannot reproduce the baseline model, there is probably something wrong with the setup that you have. Which model are you currently attempting to train? To better isolate the issue, try evaluating with one of the checkpoints provided and seeing if you can reproduce the numbers there.

**Comment by Rkyzzy** [comment]
Hi I'm facing the same issue here, may I know how did you solve it? @lee8856    @katieluo88

**Comment by lee8856** [comment]
> Hi I'm facing the same issue here, may I know how did you solve it? @lee8856 @katieluo88

Hi! maybe you can check the config file(e.g. baseline_large_ptsrep_smerf.py), and set the ### _collection='data_dict_subset_A_val'_  ,default is collection='data_dict_sample_train'

**Comment by Rkyzzy** [comment]
> > Hi I'm facing the same issue here, may I know how did you solve it? @lee8856 @katieluo88
> 
> Hi! maybe you can check the config file(e.g. baseline_large_ptsrep_smerf.py), and set the ### _collection='data_dict_subset_A_val'_ ,default is collection='data_dict_sample_train'

Hi thanks for the reply, I haven't tried using the full subset A. Instead I create a val and test from the sample data, I change collection='data_dict_sample_train' to collection='data_dict_sample_val' (which is mannually created by my own), but it seems that it is still "TOP_ll: 0.0000, TOP_lt: 0.0000", maybe I'll try use the full subsetA as you did. I'm just wondering why the sample doesn't work. Thank you very much.

**Comment by lee8856** [comment]
> > > Hi I'm facing the same issue here, may I know how did you solve it? @lee8856 @katieluo88
> > 
> > 
> > Hi! maybe you can check the config file(e.g. baseline_large_ptsrep_smerf.py), and set the ### _collection='data_dict_subset_A_val'_ ,default is collection='data_dict_sample_train'
> 
> Hi thanks for the reply, I haven't tried using the full subset A. Instead I create a val and test from the sample data, I change collection='data_dict_sample_train' to collection='data_dict_sample_val' (which is mannually created by my own), but it seems that it is still "TOP_ll: 0.0000, TOP_lt: 0.0000", maybe I'll try use the full subsetA as you did. I'm just wondering why the sample doesn't work. Thank you very much.

Maybe you can try to create a val and test from a larger dataset, 'sample data' is too small. I've checked 'data_dict_sample_train.pkl' and it doesn't have much vaild topology data(most topology_lclc matrices are sparse). 
Hope that will be helpful.

**Comment by Rkyzzy** [comment]
> > > > Hi I'm facing the same issue here, may I know how did you solve it? @lee8856 @katieluo88
> > > 
> > > 
> > > Hi! maybe you can check the config file(e.g. baseline_large_ptsrep_smerf.py), and set the ### _collection='data_dict_subset_A_val'_ ,default is collection='data_dict_sample_train'
> > 
> > 
> > Hi thanks for the reply, I haven't tried using the full subset A. Instead I create a val and test from the sample data, I change collection='data_dict_sample_train' to collection='data_dict_sample_val' (which is mannually created by my own), but it seems that it is still "TOP_ll: 0.0000, TOP_lt: 0.0000", maybe I'll try use the full subsetA as you did. I'm just wondering why the sample doesn't work. Thank you very much.
> 
> Maybe you can try to create a val and test from a larger dataset, 'sample data' is too small. I've checked 'data_dict_sample_train.pkl' and it doesn't have much vaild topology data(most topology_lclc matrices are sparse). Hope that will be helpful.

Thanks you very much for you help! I also think the issue is because sample data doesn't contain much valid topology data as the DET_t is normal but DET_l is very low
