### ISSUE TITLE
MIssing process_disjoint_split.py 

### ISSUE THREAD

**Issue by zxrzju** [NVlabs/SMERF#7]
Hi,
Thanks for sharing the great work! As is shown in the paper, training with the OpenLaneV2 splits may have overfitting. Will you provide the process_disjoint_split.py and the ckpts training with geo-disjoint splits for further evaluation?

Best regards

**Comment by katieluo88** [comment]
Apologies about that; I realized I never pushed the splits! I've updated them in the `data/OpenLane-V2/` folder. 

The commands and checkpoints are still in the [Training and Evaluating on Geographically Disjoint Set](https://github.com/NVlabs/SMERF?tab=readme-ov-file#training-and-evaluating-on-geographically-disjoint-set) section. The data processing code should now work.
