### ISSUE TITLE
SD map processing

### ISSUE THREAD

**Issue by EthanJi29** [NVlabs/SMERF#8]
Hi, thanks for your great work.

I've met some problems with [SD map processing](https://github.com/NVlabs/SMERF/tree/main?tab=readme-ov-file#sd-map-processing). The speed of processing is somehow quite slow (maybe due to my network environment).
So I'm wondering if you could share the processed SD map files on releases or google drive. Thanks a lot.

Best regards

**Comment by EthanJi29** [comment]
done it when i try this time a few hours later😂 the speed became acceptable.

**Comment by Eagleflag88** [comment]
Hi,

I am currently also facing the problem of slow downloading speed.
Could you please share your processed SD map on googledrive?

Thanks

**Comment by katieluo88** [comment]
Hi! I'm incredibly sorry, but due to licensing policies I'm unfortunately unable to release a pre-processed version of the SD map information. If others can share this, I would be very grateful and include/link it in the README.
